export const ONAM_SADHYA = {
  title: 'Onam Sadhya',
  kicker: 'Onam Special',
  restaurant: 'Chopsticks Spice Malabar',
  headline: 'Celebrate Onam with a traditional Kerala Sadhya',
  description:
    'Pre-book banana-leaf sadhya for 25 & 26 August. Choose plates and a delivery slot, then message the restaurant or place your order.',
  /** Homepage launch + Onam marketing copy (Chopsticks storefront). */
  launchBadge: 'Our new website is live',
  launchHeadline: 'Onam Sadhya — pre-book online in minutes',
  launchSupport:
    'Traditional Kerala sadhya for 25 & 26 August. Dine-in or parcel — book here, or message us on WhatsApp.',
  launchCtaPrimary: 'Pre-book Onam Sadhya',
  launchCtaPrimaryMl: 'ഓണം സദ്യ പ്രീ-ബുക്ക് ചെയ്യുക',
  launchCtaWhatsApp: 'Ask on WhatsApp',
  imageUrl: '/images/tenants/spice-malabar-onam.png',
  bookingPhone: '8928945888',
  /** All Chopsticks WhatsApp CTAs (enquiry, footer, Onam order) use this number. */
  enquiryWhatsAppPhone: '8928945888',
  enquiryWhatsAppMessage: [
    'Hi Chopsticks Spice Malabar!',
    "I'm interested in pre-booking Onam Sadhya for 25 or 26 August.",
    'Could you please share availability for dine-in and parcel, and how I can book?',
    '',
    '---',
    '',
    'ഹായ് ചോപ്സ്റ്റിക്സ് സ്പൈസ് മലബാർ!',
    'ഓണം സദ്യ ഓഗസ്റ്റ് 25 അല്ലെങ്കിൽ 26-ന് പ്രീ-ബുക്ക് ചെയ്യാൻ താൽപ്പര്യമുണ്ട്.',
    'ഡൈൻ-ഇൻ / പാർസൽ ലഭ്യതയും ബുക്കിംഗ് വിവരങ്ങളും അറിയിക്കാമോ?',
  ].join('\n'),
  /** Default delivery address locality for Onam parcel orders (Viman Nagar). */
  defaultCity: 'Pune',
  defaultState: 'Maharashtra',
  /** Own-delivery radius from the Viman Nagar kitchen. */
  deliveryRadiusKm: 8,
  deliveryAreaName: 'Viman Nagar',
  hoursLabel: '11:00 AM – 9:00 PM',
  slotStartHour: 11,
  slotEndHour: 21,
  minPlates: 1,
  maxPlates: 50,
  dates: [
    { value: '2026-08-25', label: 'Tue, 25 August' },
    { value: '2026-08-26', label: 'Wed, 26 August' },
  ],
  services: {
    dine_in: {
      id: 'dine_in' as const,
      label: 'Dine-in / table',
      price: 630,
      dishSlug: 'onam-sadhya-dine-in',
      dishName: 'Onam Sadhya (Dine-in)',
    },
    parcel: {
      id: 'parcel' as const,
      label: 'Parcel / delivery',
      price: 720,
      dishSlug: 'onam-sadhya-parcel',
      dishName: 'Onam Sadhya (Parcel)',
    },
  },
  includes: [
    'Ela (banana leaf)',
    'Salt',
    'Banana chips',
    'Sarkaravaratti',
    'Pazham (banana)',
    'Mango achar',
    'Lime pickle',
    'Inji puli',
    'Kondattam',
    'Pineapple pachadi',
    'Beetroot kichadi',
    'Pavakka pachadi',
    'Kalan',
    'Olan',
    'Thoran',
    'Mezhupurathy',
    'Theeyal',
    'Kootu curry',
    'Erissery',
    'Avial',
    'Rice',
    'Dal',
    'Ghee',
    'Sambar',
    'Rasam',
    'Buttermilk',
    'Palada payasam',
    'Parippu pradhaman',
  ],
} as const

export type OnamServiceId = keyof typeof ONAM_SADHYA.services
export type OnamDateValue = (typeof ONAM_SADHYA.dates)[number]['value']
