export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  MENU: '/menu',
  DISH_DETAILS: (slug: string) => `/menu/${slug}`,
  GALLERY: '/gallery',
  CONTACT: '/contact',
  PARTY_ORDER: '/party-order',
  LOGIN: '/login',
  REGISTER: '/register',
  PROFILE: '/profile',
  ORDERS: '/orders',
  ORDER_DETAILS: (orderId: string) => `/orders/${orderId}`,
  CART: '/cart',
  CHECKOUT: '/checkout',
  ORDER_SUCCESS: '/order-success',
  ADDRESSES: '/addresses',
  ADMIN: {
    LOGIN: '/admin/login',
    DASHBOARD: '/admin',
    CATEGORIES: '/admin/categories',
    DISHES: '/admin/dishes',
    ORDERS: '/admin/orders',
    CUSTOMERS: '/admin/customers',
    DELIVERY: '/admin/delivery',
    OFFERS: '/admin/offers',
    REPORTS: '/admin/reports',
    PARTY_INQUIRIES: '/admin/party-inquiries',
    SETTINGS: '/admin/settings',
  },
} as const
