export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  MENU: '/menu',
  LIGHT_MENU: '/menu/light',
  DISH_DETAILS: (slug: string) => `/menu/${slug}`,
  GALLERY: '/gallery',
  CONTACT: '/contact',
  PRIVACY: '/privacy',
  PARTY_ORDER: '/party-order',
  ONAM: '/onam',
  LOGIN: '/login',
  REGISTER: '/register',
  PROFILE: '/profile',
  ORDERS: '/orders',
  ORDER_DETAILS: (orderId: string) => `/orders/${orderId}`,
  ORDER_INVOICE: (orderId: string) => `/orders/${orderId}/invoice`,
  /** Public phone/counter payment page (order details + UPI QR). */
  ORDER_PAYMENT_SHARE: (token: string) => `/pay/${token}`,
  CART: '/cart',
  CHECKOUT: '/checkout',
  ORDER_SUCCESS: '/order-success',
  ADDRESSES: '/addresses',
  FAVORITES: '/favorites',
  NOTIFICATIONS: '/notifications',
  QR_MENU: (tableCode: string) => `/qr/${tableCode}`,
  BRANCH_MENU: (slug: string) => `/b/${slug}`,
  MASTER: {
    LOGIN: '/master/login',
    DASHBOARD: '/master',
    TENANTS: '/master/tenants',
    ONBOARD: '/master/tenants/new',
    FEATURES: '/master/features',
    featuresForOrg: (orgId: string) =>
      `/master/features?org=${encodeURIComponent(orgId)}`,
    tenant: (orgId: string) => `/master/tenants/${orgId}`,
  },
  ADMIN: {
    LOGIN: '/admin/login',
    DASHBOARD: '/admin',
    CATEGORIES: '/admin/categories',
    DISHES: '/admin/dishes',
    ORDERS: '/admin/orders',
    PHONE_ORDER: '/admin/phone-order',
    CUSTOMERS: '/admin/customers',
    DELIVERY: '/admin/delivery',
    DELIVERY_PARTNERS: '/admin/delivery-partners',
    OFFERS: '/admin/offers',
    ONAM_ORDERS: '/admin/onam-orders',
    REPORTS: '/admin/reports',
    PARTY_INQUIRIES: '/admin/party-inquiries',
    BRANCHES: '/admin/branches',
    QR_TABLES: '/admin/qr-tables',
    SETTINGS: '/admin/settings',
  },
  DELIVERY: {
    LOGIN: '/delivery/login',
    DASHBOARD: '/delivery',
    ORDER: (deliveryId: string) => `/delivery/${deliveryId}`,
  },
  PLATFORM: {
    HOME: '/',
    DEMO: '/demo',
  },
} as const
